# Generated by Django 2.1.7 on 2019-03-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='status',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
